{{- if .Values.global.createIngress -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
{{- if .Values.global.certManager.installed }}
    acme.cert-manager.io/http01-edit-in-place: "true"
    cert-manager.io/issue-temporary-certificate: "true"
    cert-manager.io/issuer: letsencrypt-{{ .Release.Namespace }}-spin
    kubernetes.io/tls-acme: "true"
{{- end }}
{{- if .Values.ssdopa.ingress.annotations }}
{{ tpl (toYaml .Values.ssdopa.ingress.annotations) . | indent 4 }}
{{- end }}
  name: ssd-opa-ingress
spec:
  rules:
  - host: {{ .Values.ssdopa.ingress.host }}
    http:
      paths:
      - backend:
          service:
            name: ssd-opa
            port:
              number: 8200
        path: /
        pathType: ImplementationSpecific
{{- if .Values.global.ssl.enabled }}
  tls:
  - hosts:
    - {{ .Values.ssdopa.ingress.host }}
{{ toYaml .Values.ssdopa.ingress.tls | indent 4 }}
{{- end }}
{{- end }}
