apiVersion: v1
kind: ServiceAccount
metadata:
  name: ssd-kubernetes-detector-{{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubernetes-detector-{{ .Release.Namespace }}
rules:
- apiGroups: [""]
  resources: ["pods", "namespaces", "nodes"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubernetes-detector-{{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: ssd-kubernetes-detector-{{ .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: kubernetes-detector-{{ .Release.Namespace }}
  apiGroup: rbac.authorization.k8s.io
