# Secret
apiVersion: v1
kind: Secret
metadata:
  name: poc-passwords
type: Opaque
data:
  admin-password: {{  randAlphaNum 16| b64enc | quote }}
  user1-password: {{  randAlphaNum 16| b64enc | quote }}
