apiVersion: v1
data:
  ssd-gate-config.yaml: |
    {{- tpl (.Files.Get "config/ssd-gate/config-dex.yaml") . | nindent 4 }}
kind: ConfigMap
metadata:
  name: ssd-gate-config
  labels:
    app: ssd
    component: gate
{{ include "oes.standard-labels" . | indent 4 }}

