# Secret
apiVersion: v1
kind: Secret
metadata:
  name: ssd-initial-password
type: Opaque
data:
  ADMIN_PASSWORD: {{  randAlphaNum 16| b64enc | quote }}
  USER1_PASSWORD: {{  randAlphaNum 16| b64enc | quote }}
