ssd_baseurl: http://localhost:8080

#auth_type: "poclogin"  # Defaulting so Dex config is not required
auth_type: "dex_oidc"  # This is need to tell the "type" of authentication
auth2_oidc:
  client_id: ssd-gate
  client_secret: "encrypted:gate-dex-client-secret:client-secret"
  #well_known_url: "/dex/.well-known/openid-configuration"
  userinfo_url: "/dex/userinfo"
  entity_map:
    user_name: email
  endpoint:
    auth_url:  "/dex/auth"
    token_url: "/dex/token"
  scopes:
    - openid
    - offline_access
