{{- if .Values.global.stormdriver }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: stormdriver
  name: stormdriver
spec:
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: http
      port: 7002
      protocol: TCP
      targetPort: 7002
  selector:
    app: stormdriver
  sessionAffinity: None
  type: ClusterIP
{{- end }}
