apiVersion: v1
kind: ConfigMap
metadata:
  name: supplychain-api
  labels:
    app: ssd
{{ include "oes.standard-labels" . | indent 4 }}
    component: ssd-supplychainapi
data:
{{ (tpl (.Files.Glob "config/supplychain-api/supplychain-api.yaml").AsConfig . ) | indent 2 }}
