apiVersion: v1
kind: ConfigMap
metadata:
  name: tool-chain
  labels:
    app: ssd
{{ include "oes.standard-labels" . | indent 4 }}
    component: ssd-toolchain
data:
{{ (tpl (.Files.Glob "config/tool-chain/tool-chain.yaml").AsConfig . ) | indent 2 }}
