apiVersion: v1
kind: ConfigMap
metadata:
  name: tool-chain
  labels:
    app: ssd
{{ include "oes.standard-labels" . | indent 4 }}
    component: ssd-toolchain
data:
  tool-chain.yaml: |
    {{- tpl (.Files.Get "config/tool-chain/tool-chain.yaml") . | indent 4 }}
