apiVersion: v1
kind: ConfigMap
metadata:
  name: supplychain-preprocessor
  labels:
    app: oes 
{{ include "oes.standard-labels" . | indent 4 }}
    component: oes-supplychain-preprocessor
data:
{{ (tpl (.Files.Glob "config/oes-supplychain-preprocessor/globalConfig.yaml").AsConfig . ) | indent 2 }}
{{ (tpl (.Files.Glob "config/oes-supplychain-preprocessor/jenkinsConfig.yaml").AsConfig . ) | indent 2 }}
{{ (tpl (.Files.Glob "config/oes-supplychain-preprocessor/spinnakerConfig.yaml").AsConfig . ) | indent 2 }}

