apiVersion: apps/v1
kind: Deployment
metadata:
  name: supplychain-preprocessor
  labels:
    app: oes
    component: oes-supplychain-preprocessor
{{ include "oes.standard-labels" . | indent 4 }}    
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oes
      component: oes-supplychain-preprocessor
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: oes
        component: oes-supplychain-preprocessor
{{ include "oes.standard-labels" . | indent 8 }}
      annotations:
{{- if .Values.supplychainpreprocessor.annotations -}}
        {{ toYaml .Values.supplychainpreprocessor.annotations | nindent 8 }}
{{- end }}
    spec:
      containers:
      - name: oes-supplychain-preprocessor
        image: {{ template "supplychainpreprocessor.image" . }}
        ## Add liveness and readiness 
        resources: {}
        volumeMounts:
        - mountPath: /etc/config
          name: preprocessor-volume
      imagePullSecrets:
        - name: opsmx11-secret
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
      - name: preprocessor-volume
        secret:
          secretName: supplychain-preprocessor
      securityContext:
        runAsNonRoot: true
      {{- if .Values.imagePullSecret }}
      imagePullSecrets:
      - name: {{ .Values.imagePullSecret }}
      {{- end }}

