{{- if (eq .Values.installationMode "SSD-SPIN") -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: supplychain-api
  labels:
    app: oes
    component: oes-supplychain-api
{{ include "oes.standard-labels" . | indent 4 }}
  name: supplychain-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oes
      component: oes-supplychain-api
  template:
    metadata:
      labels:
        app: oes
        component: oes-supplychain-api
{{ include "oes.standard-labels" . | indent 8 }}
      annotations:
{{- if .Values.supplychainapi.annotations -}}
        {{ toYaml .Values.supplychainapi.annotations | nindent 8 }}
{{- end }}
    spec:
      volumes:
        - name: supplychain-api-volume
          secret:
            secretName: supplychain-api
            items:
              - key: app-config.yaml
                path: app-config.yaml
            defaultMode: 420
      containers:
        - name: supplychain-api
          image: {{ template "supplychainapi.image" . }}
          ports:
            - containerPort: 8099
              protocol: TCP
          volumeMounts:
            - name: supplychain-api-volume
              mountPath: /app/app-config.yaml
              subPath: app-config.yaml
      {{- if .Values.imagePullSecret }}
      imagePullSecrets:
      - name: {{ .Values.imagePullSecret }}
      {{- end }}
      restartPolicy: Always
      securityContext: {}
{{- end -}}
