{{- if (eq .Values.installationMode "SSD-SPIN") -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tool-chain
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
{{- end -}}
