apiVersion: v1
data:
  approved_build_server: {{ toYaml .Values.global.jenkinsurl | b64enc }}
  authorized_artifact_repo: {{ toYaml .Values.global.dockerdetails | b64enc }}
  image_containers: {{ toYaml .Values.global.repocreds | b64enc }}
  opsmx_creds: {{ toYaml .Values.global.opsmxcreds | b64enc }}
  source_code: {{ toYaml .Values.global.sourcecode | b64enc }}
  sonarQube_creds: {{ toYaml .Values.global.sonarqubecreds | b64enc }}
  openAI_creds: {{ toYaml .Values.global.openaicreds | b64enc }}
  semgrep_webApi_token: {{ toYaml .Values.global.semgrepwebApitoken | b64enc }}
kind: Secret
metadata:
  name: ssdsecret
type: Opaque
