apiVersion: v1
data:
  token: |
    {{- tpl (.Files.Get "config/automation/token.json") . | nindent 4 }}
kind: ConfigMap
metadata:
  name: test-cm
  labels:
    app: ssd
    component: automation
{{ include "oes.standard-labels" . | indent 4 }}

