---
# Source: SSD/templates/roles/ssd-qa-spinnaker-spinnaker.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ssd-role-rb-argocd-ssd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ssd-role-argocd-ssd
subjects:
- kind: ServiceAccount
  name: default
  namespace: argocd-ssd
