apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "oes.fullname" . }}-datasource-creation
  labels:
{{ include "oes.standard-labels" . | indent 4 }}
data:
{{ (tpl (.Files.Glob "config/dgraph/schema.graphql").AsConfig . ) | indent 2 }}
