apiVersion: v1
kind: ServiceAccount
metadata:
  name: dgraph-schema-configure-{{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dgraph-schema-configure-{{ .Release.Namespace }}
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get","create","watch","update","patch","delete","list"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get","create","watch","update","patch","delete","list"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get","create","watch","update","patch","delete","list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dgraph-schema-configure-{{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: dgraph-schema-configure-{{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: dgraph-schema-configure-{{ .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
