---
# Source: SSD/charts/minio/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: ssd-minio
  labels:
    app: minio
    chart: minio-8.0.9
    release: ssd
    heritage: Helm
type: Opaque
data:
  accesskey: "c3Bpbm5ha2VyYWRtaW4="
  secretkey: "c3Bpbm5ha2VyYWRtaW4="
