---
# Source: SSD/charts/minio/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "ssd-minio"
  namespace: "argocd-ssd"
  labels:
    app: minio
    chart: minio-8.0.9
    release: "ssd"
