apiVersion: v1
kind: Service
metadata:
  labels:
    app: ssd
    component: ui
{{ include "oes.standard-labels" . | indent 4 }}
{{- if .Values.ui.serviceAnnotations }}
  annotations:
{{ toYaml .Values.ui.serviceAnnotations | indent 4 }}
{{- end }}
  name: ssd-ui
spec:
  type: {{ .Values.UIServiceType }}
  ports:
  - name: "https"
    port: 443
    targetPort: 8080
  - name: "http"
    port: 8080
    targetPort: 8080
    {{- if eq .Values.UIServiceType "LoadBalancer" }}
  - name: "lbhttp"
    port: 80
    targetPort: 8080
    {{- end }}
  selector:
    app: ssd
    component: ui
