apiVersion: v1
data:
{{ (tpl (.Files.Glob "config/oes-ui/app-config.json").AsConfig . ) | indent 2 }}
{{ (tpl (.Files.Glob "config/oes-ui/help-text.json").AsConfig . ) | indent 2 }}
kind: ConfigMap
metadata:
  name: ssd-ui-config
  labels:
    app: ssd
    component: ui
{{ include "oes.standard-labels" . | indent 4 }}
