apiVersion: v1
data:
{{ (tpl (.Files.Glob "config/oes-ui/nginx.conf").AsConfig . ) | indent 2 }}

kind: ConfigMap
metadata:
  name: ssd-ui-nginxconf
  labels:
    app: ssd
    component: ui
{{ include "oes.standard-labels" . | indent 4 }}
