---
# Source: SSD/templates/supplychain-preprocessor/ssd-preprocessor-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: supplychain-preprocessor
  labels:
    app: oes
    heritage: "Helm"
    release: "ssd"
    chart: "SSD-4.0.9"
    component: oes-supplychain-preprocessor
stringData:
  globalConfig.yml: "plugins: \n  - argocd\n  - jenkins\n  - spinnaker\nloglevel: info\n"
  jenkinsConfig.yml: |
    rabbitmq:
      username: 'rabbitmq'
      password: 'Networks123'
      host: rabbitmq-service
      port: 5672
      queue: jenkins-ssd
      exchange: jenkins.events
      bindingKey: jenkins-ssd
      prefetchCount: 20
  
    postgresql:
      ssddb:
        connectString: host=oes-db user='postgres' password='networks123' database=ssddb port=5432
  
    ssdopasvc:
      host: http://ssd-opa
      port: 8200
  spinnakerConfig.yml: |
    rabbitmq:
      username: 'rabbitmq'
      password: 'Networks123'
      host: rabbitmq-service
      port: 5672
      queue: isd-to-preview-saas
      exchange: echo.events
      bindingKey: preview-saas-ssd
      prefetchCount: 20
    postgresql:
      ssddb:
        connectString: host=oes-db user='postgres' password='networks123' database=ssddb port=5432
  
    toolchainsvc:
      host: http://tool-chain
      port: 8100
  
    ssdopasvc:
      host: http://ssd-opa
      port: 8200
  argocdConfig.yml: |
    rabbitmq:
      username: 'rabbitmq'
      password: 'Networks123'
      host: rabbitmq-service
      port: 5672
      queue: argo-ssd
      exchange: argo.events
      bindingKey: argo-ssd
      prefetchCount: 30
  
    postgresql:
      ssddb:
        connectString: host=oes-db user='postgres'  password='networks123' database=ssddb port=5432
