apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: token-machine-rb-{{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: token-machine-{{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: token-machine
  namespace: {{ .Release.Namespace }}
