---
# Source: SSD/templates/ssd-opa/ssd-opa-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssd-opa
  labels:
    app: oes
    component: oes-ssd-opa
    heritage: "Helm"
    release: "ssd"
    chart: "SSD-4.0.9"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oes
      component: oes-ssd-opa
  template:
    metadata:
      labels:
        app: oes
        component: oes-ssd-opa
        heritage: "Helm"
        release: "ssd"
        chart: "SSD-4.0.9"
      annotations:
    spec:
      containers:
        - name: ssd-opa
          image: genos1998/ssd-opa:v310
          ports:
            - containerPort: 8200
              protocol: TCP
          volumeMounts:
            - mountPath: /app/secrets/
              name: ssdsecret
              readOnly: true
            - mountPath: /app/scanFiles
              name: scanfilepath
            - name: ssd-opa-volume
              mountPath: /app/config/ssd-opa.yaml
              subPath: ssd-opa.yaml
          readinessProbe:
            failureThreshold: 6
            httpGet:
              path: /health
              port: 8200
              scheme: HTTP
            periodSeconds: 20
            successThreshold: 1
            timeoutSeconds: 1
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            seccompProfile:
              type: RuntimeDefault
      volumes:
        - name: ssdsecret
          secret:
            defaultMode: 420
            items:
            - key: AESEncryptionKey
              path: ssdsecret/AESEncryptionKey
            secretName: ssdsecret
        - emptyDir: {}
          name: scanfilepath
        - name: ssd-opa-volume
          secret:
            secretName: ssd-opa
            items:
              - key: ssd-opa.yaml
                path: ssd-opa.yaml
            defaultMode: 420
