---
# Source: SSD/templates/ssd-opa/ssd-opa-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: ssd-opa
  labels:
    app: ssd
    heritage: "Helm"
    release: "ssd"
    chart: "SSD-4.0.9"
    component: oes-ssd-opa
stringData:
  ssd-opa.yaml: |
    opaIngress: http://localhost:8080/ssd-opa
    httpListenPort: 8200
    kubescapeFilePath: /app/kubescapeDir
    toolChainAddr: http://tool-chain:8100/ #default value & optional
    graphQLAddr: http://dgraph-public:8080/graphql #default value & optional
    openSSFFilePath: /app/OpenSSF #default value & optional
    semgrepFilePath: /app/semgrep #default value & optional
    sonarQubeAddr: https://sonar.opsmx.com/
    reScheduleDays: 1
    reScheduleTime: 00:00
    databases:
      ssd:
        connectString: host=oes-db user='postgres' password='networks123' database=ssddb port=5432
