apiVersion: v1
kind: ConfigMap
metadata:
  name: supplychain-api
  labels:
    app: oes
{{ include "oes.standard-labels" . | indent 4 }}
    component: oes-supplychain-api
data:
{{ (tpl (.Files.Glob "config/oes-supplychain-api/supplychain-api.yaml").AsConfig . ) | indent 2 }}
