#####################################################
# This file contains minimal configuration for using
# SSD with SAML authentication e.g with Okta SAML 2.0
#####################################################

####################################################
# Global variables can be accessed across all the charts including sub-charts
global:
  # when this flag is set to false; UI will be accessible over http instead of https
  ssl:
    enabled: false

  # If cert-manager is installed, TLS secrets will created automatically, as an 'Issuer' will be created
  # Else, the TLS secrets will need to created manually
  certManager:
    installed: false

  customCerts:
    enabled: false        # Set to true if your organization requires custom TLS certs
    secretName: oes-cacerts # Please do not change this

  ## Set to true to expose oes-ui, oes-gate services over ingress
  createIngress: true

  ## OES-UI url configuration, defaults to http://localhost:8080
  oesUI:
    protocol: http
    host: test-ssd.ryzon7-isd40.opsmx.org #localhost
    # Use below port when hostname above is an external IP instead of a hostname
    #port: 8080

    ingress:
      annotations:
        kubernetes.io/ingress.class: nginx
      tls:
        secretName: ssd-ui-ingress

###############################################################################
ssdgate:
  auth_type: saml  # saml, dex-oidc and poclogin are other valid values
  saml:
    metadata_url: https://dev-14704582.okta.com/app/exkdnjuo0wxJsOtua5d7/sso/saml/metadata
    saml_initiated_login: true

