#####################################################
# OpsMx AutoPilot and Integrated Spinnaker Delivery
# This file contains configurations for AP as well as Spinnaker
#####################################################

installationMode: SSD-SPIN
## Info related to registry where OES images are stored
imageCredentials:
  repoUrl: https://quay.io/
  # Update this is using a private repo such as ACR, ECR, GCR, JFrog, etc.
  registry: quay.io/opsmxpublic

#storageClass: standard
####################################################
# kubernetes services can be exposed to a web-UI based 3 modes
# ClusterIP (will required Ingress or some other mechanism)
# or LoadBalancer or NodePort
# OES UI, OES Gate, Spinnaker Deck and Spinnaker Gate service type
k8sServiceType: ClusterIP

####################################################
# Global variables can be accessed across all the charts including sub-charts
global:
  # Custom Images registry where all the OSS and customized images used in the helm chart are stored
  # Only update this is using a private repo such as ACR, ECR, GCR, JFrog, etc.
  customImages:
    registry: quay.io/opsmxpublic

  # when this flag is set to false; UI will be accessible over http instead of https
  ssl:
    enabled: false

  # If cert-manager is installed, TLS secrets will created automatically, as an 'Issuer' will be created
  # Else, the TLS secrets will need to created manually
  certManager:
    installed: false

  customCerts:
    enabled: false        # Set to true if your organization requires custom TLS certs
    secretName: oes-cacerts # Please do not change this

  ## Set to true to expose oes-ui, oes-gate services over ingress
  createIngress: false

  ## OES-UI url configuration
  oesUI:
    protocol: http
    host: oes.example.ops.com
    # Use below port when hostname above is an external IP instead of a hostname
    #port: 31466

    ingress:
      annotations:
        kubernetes.io/ingress.class: nginx
      tls:
        secretName: oes-ui-ingress

  sourcecode:
    github:
      rest_api_url: "https://api.github.com"
      token: "xxxxxxxxxxxx" # Update the github token id
    slack:
      channel: "xxxxx"    # Update the slack channel name
      token: "xxxxxxxxxx" # Update the slack token id

  # Minio access/secret keys for the in-cluster S3 usage
  # Minio is not exposed publically
  minio:
    enabled: true
    image:
      repository: quay.io/opsmxpublic/minio
      tag: RELEASE.2020-01-03T19-12-21Z
    mcImage:
      repository: quay.io/opsmxpublic/minio-mc
      tag: RELEASE.2020-11-25T23-04-07Z
    service:
      type: ClusterIP
    accessKey: spinnakeradmin
    secretKey: spinnakeradmin
    region: us-east-1
    #Below is the securityContext block for only for K8S
    securityContext:
      enabled: true
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
    buckets:
    - name: "spinnaker"
      policy: none
      purge: false
    - name: "autopilot"
      policy: none
      purge: false
    defaultBucket:
      enabled: true
      name: "spinnaker"
    nodeSelector: {}
    affinity: {}
    tolerations: []
    persistence:
      enabled: true
      size: 10Gi
###############################################################################
# Initial passwords for users to login
#pocpasswords:
#  admin:
#    password: {{ randAlphaNum 16 | quote }}
#  user1:
#    password: {{ randAlphaNum 16 | quote }}
db:
  ## Set it to false if any external database is to be used
  enabled: true

  ## Change the default configuration when above option is set to false
  ## Below url and credentials are used by Autopilot & Sapor
  url: jdbc:postgresql://oes-db:5432
  username: postgres
  password: networks123

  ## Image specific details
  image:
    repository: ubi8-oes-db
    tag: v3.0.0-ssd
    pullPolicy: IfNotPresent

  annotations:
    moniker.spinnaker.io/application: isd

  serviceAnnotations: {}

  ## Strategy to rollout statefulset pods
  podManagementPolicy: OrderedReady

  ## Default group to which the default user of a pod belongs and it applies only to K8S
  securityContext:
    fsGroup: 1000

  ## storageMountSize is the size with which a PVC is to be created
  storageMountSize: 8Gi

####################################################
toolchain:
  ## Image specific details
  image:
    repository: tool-chain
    tag: v4.0.4-rc4
    pullPolicy: IfNotPresent

  annotations:
    moniker.spinnaker.io/application: isd

  serviceAnnotations: {}

####################################################
supplychainpreprocessor:
  ## Image specific details
  image:
    repository: supplychain-preprocessor
    tag: v4.0.4-rc4
    pullPolicy: IfNotPresent

  annotations:
    moniker.spinnaker.io/application: isd

  serviceAnnotations: {}
  
####################################################
ssdopa:
  ## Image specific details
  image:
    repository: ssd-opa
    tag: v4.0.4-rc4
    pullPolicy: IfNotPresent

  annotations:
    moniker.spinnaker.io/application: isd

  serviceAnnotations: {}

  persistence:
    size: 5Gi
    accessMode: ReadWriteOnce

  ingress:
    protocol: http
    host: SSD.DNS.COMPANY.COM

    annotations:
      kubernetes.io/ingress.class: nginx
    tls:
      secretName: ssd-opa-ingress
####################################################
supplychainapi:
  ## Image specific details
  image:
    repository: supplychain-api
    tag: v4.0.4-rc4
    pullPolicy: IfNotPresent

  annotations:
    moniker.spinnaker.io/application: isd

  serviceAnnotations: {}

###############################################################################
## Details of rabbitmq message bus image for OES
##
rabbitmq:
  ## rabbitmq  endpoint that is used by oes-gate and oes-platform for caching;
  ## Change this to custom URL if installRedis is set to false
  url: rabbitmq-service
  port: 5672
  username: rabbitmq
  password: Networks123
  image:
    registry: quay.io/opsmxpublic/rabbitmq
    repository: 3-management

  annotations:
    moniker.spinnaker.io/application: isd

  serviceAnnotations: {}

  #Blow block is for only for K8S
  securityContext:
    fsGroup: 1000
    
###############################################################################
## Values of OES UI
ui:
  ## Image specific details
  image:
    repository: ubi8-oes-ui
    tag: v4.0.4-rc7
    pullPolicy: IfNotPresent

  annotations:
    moniker.spinnaker.io/application: "isd"

  serviceAnnotations: {}

  config:
    ## Interval, in millsecs, at which UI refreshes application dashboard
    setApplicationRefreshInterval: 300000

# Leave it as true, even if not using OPA
opa:
  enabled: true
  image:
    repository: opa
    tag: v0.47.0
    pullPolicy: IfNotPresent
  annotations:
    moniker.spinnaker.io/application: isd

###############################################################################################
#### The values below this line are best not changed except in rare situations
###############################################################################################
dex:
  configSecret:
    create: false
    name: "gate-dex-config"
  volumes:
    - name: gate-dex-client-secret
      secret:
        defaultMode: 420
        secretName: gate-dex-client-secret
  env:
    - name: GATE_CLIENT_SECRET
      valueFrom:
        secretKeyRef:
          name: gate-dex-client-secret
          key: client-secret
