httpListenPort: 8200
graphQLAddr: http://graphql-server:8080/query
reScheduleDays: 20
reScheduleTime: 00:00
databases:
  ssd:
    connectString: host=oes-db user='postgres' password='networks123' database=ssddb port=5432
