apiVersion: apps/v1
kind: Deployment
metadata:
  name: supplychain-preprocessor
  labels:
    app: ssd
    component: oes-supplychain-preprocessor
{{ include "oes.standard-labels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ssd
      component: oes-supplychain-preprocessor
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ssd
        component: oes-supplychain-preprocessor
{{ include "oes.standard-labels" . | indent 8 }}
      annotations:
{{- if .Values.supplychainpreprocessor.annotations -}}
        {{ toYaml .Values.supplychainpreprocessor.annotations | nindent 8 }}
{{- end }}
    spec:
      containers:
      - name: oes-supplychain-preprocessor
        image: {{ template "supplychainpreprocessor.image" . }}
        envFrom:
        - configMapRef:
            name: ssd-proxy-certs
            optional: true
        volumeMounts:
        - mountPath: /etc/ssd-public-keys
          name: ssd-public-keys
        - mountPath: /tmp
          name: tmp
        - mountPath: /etc/config
          name: preprocessor-volume
        - mountPath: /etc/secrets/
          name: ssdsecret
          readOnly: true
        - mountPath: /etc/secrets/supplychain-preprocessor-token/
          name: token
          readOnly: true
        - mountPath: /usr/local/share/ca-certificates
          name: custom-certs
        readinessProbe:
          failureThreshold: 6
          httpGet:
            path: /healthz
            port: 8058
            scheme: HTTP
          periodSeconds: 20
          successThreshold: 1
          timeoutSeconds: 1
        securityContext:
      {{- if .Values.supplychainpreprocessor.securityContext }}
      {{ toYaml .Values.supplychainpreprocessor.securityContext | nindent 12 }}
      {{- else }}
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            seccompProfile:
              type: RuntimeDefault
      {{- end }}


      imagePullSecrets:
        - name: opsmx11-secret
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: ssd-public-keys
        name: ssd-public-keys
      - emptyDir: {}
        name: tmp
      - name: preprocessor-volume
        secret:
          secretName: supplychain-preprocessor
      - name: ssdsecret
        secret:
          defaultMode: 420
          items:
          - key: AESEncryptionKey
            path: ssdsecret/AESEncryptionKey
          secretName: ssdsecret
      - name: ssd-proxy-certs
        configMap:
          defaultMode: 420
          optional: true
          name: ssd-proxy-certs
      - name: token
        secret:
          defaultMode: 420
          secretName: supplychain-preprocessor-token
      - name: custom-certs  # Optional: In case we are using any customer-specific custom CAs
        configMap:
          defaultMode: 420
          items:
          - key: ca.crt
            path: ca.crt
          optional: true
          name: customer-custon-ca
      securityContext:
        runAsNonRoot: true
      {{- if .Values.imagePullSecret }}
      imagePullSecrets:
      - name: {{ .Values.imagePullSecret }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}


