#####################################################
# This is a minimal configuration needed for SSD Installation
# Using builtin poc login
#####################################################

RabbitServiceType: NodePort

global:
  createIngress: false
  oesUI:
    protocol: http
    host: localhost
    port: 8080

noPvc: true
minio:
  mode: standalone
  persistence:
    enabled: false
ssdgate:
  installDex: false
  createGateDexSecret: false
  auth_type: poclogin

