apiVersion: apps/v1
kind: Deployment
metadata:
  name: supplychain-api
  labels:
    app: ssd
    component: supplychain-api
{{ include "oes.standard-labels" . | indent 4 }}
  name: supplychain-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ssd
      component: supplychain-api
  template:
    metadata:
      labels:
        app: ssd
        component: supplychain-api
{{ include "oes.standard-labels" . | indent 8 }}
      annotations:
{{- if .Values.supplychainapi.annotations -}}
        {{ toYaml .Values.supplychainapi.annotations | nindent 8 }}
{{- end }}
    spec:
      volumes:
        - name: docker-sock
          hostPath:
            path: /var/run
            type: 'adfsdf'
        - name: sbom
          persistentVolumeClaim:
            claimName: supplychain-api
        - name: supplychain-api-volume
          configMap:
            name: supplychain-api
            items:
              - key: supplychain-api.yaml
                path: supplychain-api.yaml
            defaultMode: 420
      containers:
        - name: supplychain-api
          image: {{ template "supplychainapi.image" . }}
          ports:
            - containerPort: 8099
              protocol: TCP
          volumeMounts:
            - name: sbom
              mountPath: /tools/sbom
            - name: supplychain-api-volume
              mountPath: /tools/config/supplychain-api.yaml
              subPath: supplychain-api.yaml
            - name: docker-sock
              mountPath: /var/run
      {{- if .Values.imagePullSecret }}
      imagePullSecrets:
      - name: {{ .Values.imagePullSecret }}
      {{- end }}
      restartPolicy: Always
      securityContext: {}