apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ssd
    component: carina-instance
{{ include "oes.standard-labels" . | indent 4 }}
  name: tool-chain
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ssd
      component: tool-chain
  template:
    metadata:
      labels:
        app: ssd
        component: tool-chain
{{ include "oes.standard-labels" . | indent 8 }}
      annotations:
{{- if .Values.toolchain.annotations -}}
        {{ toYaml .Values.toolchain.annotations | nindent 8 }}
{{- end }}
    spec:
      volumes:
        - name: docker-sock
          hostPath:
            path: /var/run
            type: ''
        - name: sbom
          persistentVolumeClaim:
            claimName: tool-chain
        - name: tool-chain-volume
          configMap:
            name: tool-chain
            items:
              - key: tool-chain.yaml
                path: tool-chain.yaml
            defaultMode: 420
      containers:
        imagePullPolicy: IfNotPresent
        - name: tool-chain
          image: {{ template "toolchain.image" . }}
          ports:
            - containerPort: 8100
              protocol: TCP
          volumeMounts:
            - name: sbom
              mountPath: /tools/sbom
            - name: tool-chain-volume
              mountPath: /tools/config/tool-chain.yaml
              subPath: tool-chain.yaml
            - name: docker-sock
              mountPath: /var/run
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      {{- if .Values.imagePullSecret }}
      imagePullSecrets:
      - name: {{ .Values.imagePullSecret }}
      {{- end }}
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
