apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssd-opa
  labels:
    app: oes
    component: oes-ssd-opa
{{ include "oes.standard-labels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oes
      component: oes-ssd-opa
  template:
    metadata:
      labels:
        app: oes
        component: oes-ssd-opa
{{ include "oes.standard-labels" . | indent 8 }}
      annotations:
{{- if .Values.ssdopa.annotations -}}
        {{ toYaml .Values.ssdopa.annotations | nindent 8 }}
{{- end }}
    spec:
      containers:
        - name: ssd-opa
          image: {{ template "ssdopa.image" . }}
          ports:
            - containerPort: 8200
              protocol: TCP
          volumeMounts:
            - name: kubescapedir
              mountPath: /app/kubescapeDir
            - name: semgrep
              mountPath: /app/semgrep
            - name: openssf
              mountPath: /app/OpenSSF
            - name: ssd-opa-volume
              mountPath: /app/config/ssd-opa.yaml
              subPath: ssd-opa.yaml
          readinessProbe:
            failureThreshold: 6
            httpGet:
              path: /health
              port: 8200
              scheme: HTTP
            periodSeconds: 20
            successThreshold: 1
            timeoutSeconds: 1
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            seccompProfile:
              type: RuntimeDefault
      {{- if .Values.imagePullSecret }}
      imagePullSecrets:
      - name: {{ .Values.imagePullSecret }}
      {{- end }}
      volumes:
        - name: kubescapedir
        - name: semgrep
          persistentVolumeClaim:
            claimName: semgrep-pvc
        - name: openssf
          persistentVolumeClaim:
            claimName: openssf-pvc
        - name: ssd-opa-volume
          secret:
            secretName: ssd-opa
            items:
              - key: ssd-opa.yaml
                path: ssd-opa.yaml
            defaultMode: 420
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}


