rabbitmq:
   username: rabbitmq
    password: Networks123
    host: rabbitmq-service
    port: 5672
    queue: jenkins-ssd
    exchange: jenkins.events
    bindingKey: jenkins-ssd

postgresql:
  ssddb:
    connectString: host=oes-db user='postgres' password='networks123' database=ssddb port=5432
