{{- if (eq .Values.installationMode "SSD-SPIN") -}}
apiVersion: v1
stringData:
  GATEURL: {{ .Values.spinnaker.spinCli.gate.endpoint }}
  GATEUSER: {{ .Values.spinnaker.spinCli.auth.basic.username }}
  GATEPASS: {{ .Values.spinnaker.spinCli.auth.basic.password }}
kind: Secret
metadata:
  name: oes-gate-secret
  labels:
{{ include "oes.standard-labels" . | indent 4 }}
{{- end -}}
