{{- if (.Values.installSpinnaker) }}
{{- if .Values.spinnaker.gitopsHalyard.mTLS.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
{{- if .Values.spinDeck.ingress.annotations }}
{{ toYaml .Values.global.spinDeck.annotations | indent 4 }}
{{- end }}
    cert-manager.io/issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    nginx.ingress.kubernetes.io/proxy-ssl-secret: {{ .Release.Namespace }}/mtlscerts-pkcs12
    nginx.ingress.kubernetes.io/proxy-ssl-server-name: spin-deck.{{ .Release.Namespace }}.svc
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": before-hook-creation
  name: spinnaker-deck-ingress
spec:
  rules:
  - host: {{ .Values.global.spinDeck.host }}
    http:
      paths:
      - backend:
          service:
            name: spin-deck
            port:
              number: 9000
        path: /
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - {{ .Values.global.spinDeck.host }}
    secretName: spinnaker-deck-ingress
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
{{- if .Values.global.spinGate.annotations }}
{{ toYaml .Values.global.spinGate.annotations | indent 4 }}
{{- end }}
    cert-manager.io/issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    nginx.ingress.kubernetes.io/proxy-ssl-secret: {{ .Release.Namespace }}/mtlscerts-pkcs12
    nginx.ingress.kubernetes.io/proxy-ssl-server-name: spin-gate.{{ .Release.Namespace }}.svc
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": before-hook-creation
  name: spinnaker-gate-ingress
spec:
  rules:
  - host: {{ tpl .Values.global.spinGate.host . }}
    http:
      paths:
      - backend:
          service:
            name: spin-gate
            port:
              number: 8084
        path: /
        pathType: ImplementationSpecific
      - backend:
          service:
            name: spin-gate
            port:
              number: 8084
        path: /login
        pathType: ImplementationSpecific
      - backend:
          service:
            name: spin-gate
            port:
              number: 8084
        path: /auth/*
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - {{ .Values.global.spinGate.host }}
    secretName: spinnaker-gate-ingress
{{- end }}
{{- end }}
