signingKeys:
  publicKeyConfigmapName: ssd-public-keys
  secretKeyNamePrefix: jwtrsa
  regenerateInterval: 15768000
  keyLengthBits: 2048
managedSecrets:
  regenerateInterval: 10800 # seconds
  secrets:
    - name: ssd-gate-token # the k8s name for this token
      serviceName: ssd-gate
      authorizations:
        - generate-user-token
    - name: supplychain-api-token
      serviceName: supplychain-api
      authorizations:
        - generate-serviceaccount-token
        - access-dgraph
    - name: ssd-opa-token
      serviceName: ssd-opa
      authorizations:
        - access-dgraph
    - name: tool-chain-token
      serviceName: tool-chain
      authorizations:
        - access-dgraph
    - name: supplychain-preprocessor-token
      serviceName: supplychain-preprocessor
      authorizations:
        - access-dgraph
