---
# Source: SSD/templates/ssd-gate/poc-passwords.yaml
# Secret
apiVersion: v1
kind: Secret
metadata:
  name: poc-passwords
type: Opaque
data:
  ADMIN_PASSWORD: "MlVDd3ZvdXE1Q2xhaml5SQ=="
  USER1_PASSWORD: "cnR0QmVhMEJlUWtOVGtFbQ=="
