apiVersion: v1
kind: Secret
metadata:
  name: ssd-opa
  labels:
    app: ssd
{{ include "ssd.standard-labels" . | indent 4 }}
    component: ssd-opa
stringData:
{{ (tpl (.Files.Glob "config/ssd-opa/ssd-opa.yaml").AsConfig . ) | indent 2 }}
