rabbitmq:
  username: rabbitmq
  password: Networks123
  host: rabbitmq-service
  port: 5672
  queue: argo-ssd
  exchange: argo.events
  bindingKey: argo-ssd
  prefetchCount: 30

postgresql:
  ssddb:
    connectString: host=oes-db user='postgres' password='networks123' database=ssddb port=5432
