rabbitmq:
  username: '{{ .Values.rabbitmq.username }}'
  password: '{{ .Values.rabbitmq.password }}'
  host: rabbitmq-service
  port: 5672
  queue: preview-saas-ssd
  exchange: echo.events
  bindingKey: preview-saas-ssd
postgresql:
  ssddb:
    connectString: host=oes-db user='{{ .Values.db.username }}' password='{{ .Values.db.password }}' database=ssddb port=5432

guacsvc:
  host: http://tool-chain
  port: 8100

policysvc:
  host: http://ssd-opa
  port: 8200
