rabbitmq:
  username: '{{ .Values.rabbitmq.username }}'
  password: '{{ .Values.rabbitmq.password }}'
  host: rabbitmq-service
  port: 5672
  queue: isd-to-preview-saas
  #queue: preview-saas-ssd
  exchange: echo.events
  bindingKey: preview-saas-ssd
  prefetchCount: 200
postgresql:
  ssddb:
    connectString: host={{ .Values.db.host }} user='{{ .Values.db.username }}'  password='{{ .Values.db.password }}' database=ssddb port={{ .Values.db.port }}
ssdopasvc:
  host: http://ssd-opa
  port: 8200
#toolchainsvc:
#  host: http://tool-chain
#  port: 8100


