rabbitmq:
  username: '{{ .Values.rabbitmq.username }}'
  password: '{{ .Values.rabbitmq.password }}'
  host: rabbitmq-service
  port: 5672
  queue: isd-to-preview-saas
  exchange: echo.events
  bindingKey: preview-saas-ssd
  prefetchCount: 20
postgresql:
  ssddb:
    connectString: host=oes-db user='{{ .Values.db.username }}' password='{{ .Values.db.password }}' database=ssddb port=5432

toolchainsvc:
  host: http://tool-chain
  port: 8100

ssdopasvc:
  host: http://ssd-opa
  port: 8200
