apiVersion: v1
kind: Secret
metadata:
  name: supplychain-api
  labels:
    app: ssd
{{ include "ssd.standard-labels" . | indent 4 }}
    component: supplychain-api
stringData:
{{ (tpl (.Files.Glob "config/supplychain-api/app-config.yaml").AsConfig . ) | indent 2 }}
