apiVersion: apps/v1
kind: Deployment
metadata:
  name: supplychain-api
  labels:
    app: ssd
    component: supplychain-api
{{ include "ssd.standard-labels" . | indent 4 }}
  name: supplychain-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ssd
      component: supplychain-api
  template:
    metadata:
      labels:
        app: ssd
        component: supplychain-api
{{ include "ssd.standard-labels" . | indent 8 }}
      annotations:
{{- if .Values.supplychainapi.annotations -}}
        {{ toYaml .Values.supplychainapi.annotations | nindent 8 }}
{{- end }}
    spec:
      containers:
        - name: supplychain-api
          image: {{ template "supplychainapi.image" . }}
          ports:
            - containerPort: 8099
              protocol: TCP
          envFrom:
          - configMapRef:
              name: ssd-proxy-certs
              optional: true
          readinessProbe:
            failureThreshold: 12
            httpGet:
              path: /healthz
              port: 8099
              scheme: HTTP
            periodSeconds: 20
            successThreshold: 1
            timeoutSeconds: 1
          volumeMounts:
            - mountPath: /app/ssd-public-keys
              name: ssd-public-keys
            - name: supplychain-api-volume
              mountPath: /app/app-config.yaml
              subPath: app-config.yaml
            - mountPath: /app/ssd-integrations.yaml
              name: supplychain-api-cm
              subPath: ssd-integrations.yaml
            - mountPath: /app/secrets/
              name: ssdsecret
              readOnly: true
            - mountPath: /usr/local/share/ca-certificates
              name: custom-certs
            - mountPath: /app/secrets/supplychain-api-token/
              name: token
              readOnly: true
          securityContext:
      {{- if .Values.supplychainapi.securityContext }}
      {{ toYaml .Values.supplychainapi.securityContext | nindent 12 }}
      {{- else }}
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            seccompProfile:
              type: RuntimeDefault
      {{- end }}

      {{- if .Values.imagePullSecret }}
      imagePullSecrets:
      - name: {{ .Values.imagePullSecret }}
      {{- end }}
      restartPolicy: Always
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - configMap:
            defaultMode: 420
            name: ssd-public-keys
          name: ssd-public-keys
        - name: supplychain-api-volume
          secret:
            secretName: supplychain-api
            items:
              - key: app-config.yaml
                path: app-config.yaml
            defaultMode: 420
        - configMap:
            defaultMode: 420
            items:
            - key: ssd-integrations.yaml
              path: ssd-integrations.yaml
            name: supplychain-api-cm
          name: supplychain-api-cm
        - name: ssdsecret
          secret:
            defaultMode: 420
            items:
            - key: AESEncryptionKey
              path: ssdsecret/AESEncryptionKey
            secretName: ssdsecret
        - name: ssd-proxy-certs
          configMap:
            defaultMode: 420
            optional: true
            name: ssd-proxy-certs
        - name: token
          secret:
            defaultMode: 420
            secretName: supplychain-api-token
        - name: custom-certs  # Optional: In case we are using any customer-specific custom CAs
          configMap:
            defaultMode: 420
            items:
            - key: ca.crt
              path: ca.crt
            optional: true
            name: customer-custon-ca
