---
# Source: SSD/templates/supplychain-api/ssd-supplychain-api-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: supplychain-api
  labels:
    app: oes
    heritage: "Helm"
    release: "ssd"
    chart: "SSD-4.0.9"
    component: oes-supplychain-api
stringData:
  app-config.yaml: |
    opsMxSvc: http://localhost:8080
    ssdOpa: http://ssd-opa:8200
    graphqlsvc:
        host: http://dgraph-public
        port: 8080
    postgresql:
        ssd:
          connectString: host=oes-db user='postgres'  password='networks123' database=ssddb
    toolchain:
        host: http://tool-chain
        port: 8100
    spinnaker:
        rabbitmq:
          username: 'rabbitmq'
          password: 'Networks123'
          host: rabbitmq-service
          port: 5672
          queue: isd-to-preview-saas
          exchange: echo.events
          bindingKey: preview-saas-ssd
