apiVersion: v1
kind: ConfigMap
metadata:
  name: tool-chain
  labels:
    app: ssd
{{ include "ssd.standard-labels" . | indent 4 }}
    component: toolchain
data:
{{ (tpl (.Files.Glob "config/toolchain/tool-chain.yaml").AsConfig . ) | indent 2 }}
