apiVersion: v1
kind: Service
metadata:
  labels:
    app: ssd
    component: db
{{ include "oes.standard-labels" . | indent 4 }}
{{- if .Values.db.serviceAnnotations }}
  annotations:
{{ toYaml .Values.db.serviceAnnotations | indent 4 }}
{{- end }}
  name: ssd-db
spec:
  type: ClusterIP
  ports:
  - name: db
    protocol: TCP
    port: 5432
    targetPort: 5432
  selector:
    app: ssd
    component: db
